;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Player.Shapeshifting.Transformed",DevComment="")
+GameplayTagList=(Tag="StateTree.Chase",DevComment="")
+GameplayTagList=(Tag="StateTree.Investigation",DevComment="")
+GameplayTagList=(Tag="StateTree.Routine.Idle",DevComment="")
+GameplayTagList=(Tag="StateTree.Routine.Patrol",DevComment="")

