;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="StateTree.Forget",NewTagName="StateTree.Seeking")
+GameplayTagRedirects=(OldTagName="Player.Shapeshifting.Transformed",NewTagName="Player.Shapeshifting.Possessing")
+GameplayTagRedirects=(OldTagName="Player.Movement.Crouch",NewTagName="Player.Movement.Crouching")
+GameplayTagRedirects=(OldTagName="Player.Movement.Crouching",NewTagName="Player.Movement.Crouched")
+GameplayTagRedirects=(OldTagName="Player.Movement.Jump",NewTagName="Player.Movement.Jumping")
+GameplayTagRedirects=(OldTagName="Player.Movement.Sprint",NewTagName="Player.Movement.Sprinting")
+GameplayTagRedirects=(OldTagName="Player.Movement.Walking",NewTagName="Player.Movement.Moving")
+GameplayTagRedirects=(OldTagName="Player.Movement.Falling",NewTagName="Player.Movement.Jumping")
+GameplayTagList=(Tag="Enemy.Senses.Sight",DevComment="")
+GameplayTagList=(Tag="Enemy.Status.Chasing",DevComment="")
+GameplayTagList=(Tag="Player.Movement.Crouched",DevComment="")
+GameplayTagList=(Tag="Player.Movement.Grounded",DevComment="")
+GameplayTagList=(Tag="Player.Movement.Jumping",DevComment="")
+GameplayTagList=(Tag="Player.Movement.Moving",DevComment="")
+GameplayTagList=(Tag="Player.Movement.Sprinting",DevComment="")
+GameplayTagList=(Tag="Player.Shapeshifting.Possessing",DevComment="")
+GameplayTagList=(Tag="Player.Status.Dead",DevComment="")
+GameplayTagList=(Tag="Player.Status.Healing",DevComment="")
+GameplayTagList=(Tag="StateTree.Chase",DevComment="")
+GameplayTagList=(Tag="StateTree.Investigation",DevComment="")
+GameplayTagList=(Tag="StateTree.Investigation.Radio",DevComment="")
+GameplayTagList=(Tag="StateTree.Investigation.Sight",DevComment="")
+GameplayTagList=(Tag="StateTree.Investigation.Sound",DevComment="")
+GameplayTagList=(Tag="StateTree.Routine.Idle",DevComment="")
+GameplayTagList=(Tag="StateTree.Routine.Patrol",DevComment="")
+GameplayTagList=(Tag="StateTree.Seeking",DevComment="")

